name: workflow
on:
  pull_request:
    branches:
      - main
  push:

jobs:
  lint:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-python@v6
      - uses: pre-commit/action@v3.0.1
